daspanel_web/modules/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Flaskapp

Flaskapp seed

 :copyright: (c) 2016, Abner G Jacobsen.
             All rights reserved.
 :license:   The MIT License (MIT), see LICENSE for more details.

"""
from __future__ import absolute_import, division, print_function
#from __about__ import *

daspanel_web/modules/content/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
flaskapp content module
~~~~~~~~~~~~~~~~~~~~~~~

Contains all the code you need for an Flaskapp module.

:copyright: (c) 2016 by Abner G Jacobsen
:licence: The MIT License (MIT), see LICENCE for more details
"""
from __future__ import absolute_import, division, print_function
import logging

__title__ = 'flaskapp content module'
__summary__ = 'Contains all the code you need for an Flaskapp module.'
__uri__ = 'https://github.com/daspanel/flaskapp-cookiecutter'

__version__ = '0.0.1'

__author__ = 'Abner G Jacobsen'
__email__ = 'abner@apoana.com.br'

__license__ = 'The MIT License (MIT)'
__copyright__ = 'Copyright 2016 Abner G Jacobsen'

# the user should dictate what happens when a logging event occurs
#logging.getLogger(__name__).addHandler(logging.NullHandler())

"""The content module."""
__all__ = ["views"]
from .views import *  # noqa

daspanel_web/modules/content/views.py
from flask import Blueprint, render_template
from flask_login import login_required

bp = Blueprint('content', __name__)


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    return render_template('/content/home.html')


@bp.route('/feedback', methods=['GET', 'POST'])
def feedback():
    """GET|POST /feedback: feedback form handler
    """
    form = FeedbackForm()
    if form.validate_on_submit():
        # TODO: send feedback to contact@example.com
        return 'ok'

    return render_template('/content/feedback.html', form=form)

daspanel_web/modules/module1/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
flaskapp content module
~~~~~~~~~~~~~~~~~~~~~~~

Contains all the code you need for an Flaskapp module.

:copyright: (c) 2016 by Abner G Jacobsen
:licence: The MIT License (MIT), see LICENCE for more details
"""
from __future__ import absolute_import, division, print_function
import logging

__title__ = 'flaskapp content module'
__summary__ = 'Contains all the code you need for an Flaskapp module.'
__uri__ = 'https://github.com/daspanel/flaskapp-cookiecutter'

__version__ = '0.0.1'

__author__ = 'Abner G Jacobsen'
__email__ = 'abner@apoana.com.br'

__license__ = 'The MIT License (MIT)'
__copyright__ = 'Copyright 2016 Abner G Jacobsen'

# the user should dictate what happens when a logging event occurs
#logging.getLogger(__name__).addHandler(logging.NullHandler())

"""The content module."""
__all__ = ["views"]
from .views import *  # noqa

daspanel_web/modules/module1/views.py
from flask import Blueprint, render_template
import requests
import json
from devourer import GenericAPI, APIMethod, APIError

bp = Blueprint('module1', __name__)

class TestApi(GenericAPI):
    users = APIMethod('get', '/api/?results={count}')

    def __init__(self, headers=None):
        params = {
            'url': 'https://randomuser.me',
            'auth': None,
            'load_json': True,
            'throw_on_error': True,
            'headers': headers
        }
        super(TestApi, self).__init__(**params)


@bp.route('/', methods=['GET'])
def home():
    """GET /: render homepage
    """
    myheaders={
        "pragma": "no-cache",
        "Accept": "application/json",
        "Authorization": "civmw76wg000001p2dwqxpvet",
    }

    api = TestApi(headers=myheaders)
    myusers = api.users(count=1)
    print myusers
    
    result = requests.get("https://randomuser.me/api/?results=5",
        headers={
            "pragma": "no-cache"
        },
        cookies={},
    )
    output = json.loads(result.content)
    #for rec in output['results']:
    #    print rec

    return render_template('/modules/module1/home.html', records=output['results'])

daspanel_web/modules/services/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Daspanel CP services module
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Sservices module for Daspanel web control panel.

:copyright: (c) 2017 by Abner G Jacobsen
:licence: GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
import logging

__title__ = 'Daspanel services module'
__summary__ = 'Sites module for Daspanel web control panel.'
__uri__ = 'https://github.com/daspanel/cpweb'

__version__ = '0.0.1'

__author__ = 'Abner G Jacobsen'
__email__ = 'abner@apoana.com.br'

__license__ = 'GNU General Public License v3'
__copyright__ = 'Copyright 2017 Abner G Jacobsen'

# the user should dictate what happens when a logging event occurs
#logging.getLogger(__name__).addHandler(logging.NullHandler())

"""The content module."""
__all__ = ["views"]
from .views import *  # noqa

daspanel_web/modules/services/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Daspanel CP Web

Daspanel control panel for web

 :copyright: (c) 2017, Abner G Jacobsen.
             All rights reserved.
 :license:   GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from flask_login import login_required

bp = Blueprint('services', __name__)


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    return render_template('/modules/services/home.html')

daspanel_web/modules/sites/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Daspanel CP sites module
~~~~~~~~~~~~~~~~~~~~~~~~

Sites module for Daspanel web control panel.

:copyright: (c) 2017 by Abner G Jacobsen
:licence: GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
import logging

__title__ = 'Daspanel sites module'
__summary__ = 'Sites module for Daspanel web control panel.'
__uri__ = 'https://github.com/daspanel/cpweb'

__version__ = '0.0.1'

__author__ = 'Abner G Jacobsen'
__email__ = 'abner@apoana.com.br'

__license__ = 'GNU General Public License v3'
__copyright__ = 'Copyright 2017 Abner G Jacobsen'

# the user should dictate what happens when a logging event occurs
#logging.getLogger(__name__).addHandler(logging.NullHandler())

"""The content module."""
__all__ = ["views"]
from .views import *  # noqa

daspanel_web/modules/sites/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Daspanel CP Web

Daspanel control panel for web

 :copyright: (c) 2017, Abner G Jacobsen.
             All rights reserved.
 :license:   GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from flask_login import login_required
import json
from devourer import GenericAPI, APIMethod, APIError

from .forms import (
    NewSiteForm, DeleteSiteForm, EditSiteForm,
    NewUploadHttpForm,
    ServerCmdForm,
    NewVersionForm, DeleteVersionForm, EditVersionForm,
    NewRedirectForm, DeleteRedirectForm, EditRedirectForm
)

bp = Blueprint('sites', __name__)

API_SERVER = 'http://daspanel-api:8080/1.0'

class VersionsApi(GenericAPI):
    add_version  = APIMethod('post', '/{id}/versions')
    del_version  = APIMethod('delete', '/{id}/versions/{version_id}')
    edit_version  = APIMethod('put', '/{id}/versions/{version_id}')
    get_byid = APIMethod('get', '/{id}/versions/{version_id}')

    def __init__(self, server='http://daspanel-api:8080/1.0', auth=None):
        _headers = {
            'pragma': 'no-cache',
            'Connection': 'close',
            'Accept': 'application/json',
            'Authorization': auth,
        }

        super(VersionsApi, self).__init__(
            url = '{}/sites'.format(server),
            auth = None,
            headers = _headers,
            load_json = True,
            throw_on_error = True
        )
        
    def finalize(self, name, result, *args, **kwargs):
        if self.throw_on_error and result.status_code >= 400:
            raise APIError(json.loads(result.content)['detail'], response=result.__dict__)
        if self.load_json and not result.status_code == 204:
            return json.loads(result.content)
        return result.content

class HttpServiceApi(GenericAPI):
    gen_config   = APIMethod('get', '/{server_type}/genconfig/{id}')
    del_config   = APIMethod('get', '/{server_type}/delconfig/{id}')
    enable_site  = APIMethod('get', '/{server_type}/activate/{id}')
    disable_site = APIMethod('get', '/{server_type}/deactivate/{id}')
    http_reload  = APIMethod('get', '/{server_type}/reload')

    def __init__(self, server='http://daspanel-api:8080/1.0', auth=None):
        _headers = {
            'pragma': 'no-cache',
            'Connection': 'close',
            'Accept': 'application/json',
            'Authorization': auth,
        }

        super(HttpServiceApi, self).__init__(
            url = '{}/sites/service'.format(server),
            auth = None,
            headers = _headers,
            load_json = True,
            throw_on_error = True
        )
        
    def finalize(self, name, result, *args, **kwargs):
        if self.throw_on_error and result.status_code >= 400:
            raise APIError(json.loads(result.content)['detail'], response=result.__dict__)
        if self.load_json and not result.status_code == 204:
            return json.loads(result.content)
        return result.content


class ContentApi(GenericAPI):
    http_zip   = APIMethod('post', '/{id}/remotezip')

    def __init__(self, server='http://daspanel-api:8080/1.0', auth=None):
        _headers = {
            'pragma': 'no-cache',
            'Connection': 'close',
            'Accept': 'application/json',
            'Authorization': auth,
        }

        super(ContentApi, self).__init__(
            url = '{}/sites/content'.format(server),
            auth = None,
            headers = _headers,
            load_json = True,
            throw_on_error = True
        )
        
    def finalize(self, name, result, *args, **kwargs):
        if self.throw_on_error and result.status_code >= 400:
            #print(result.content)
            raise APIError(json.loads(result.content)['detail'], response=result.__dict__)
        if self.load_json:
            return json.loads(result.content)
        return result.content


class SitesApi(GenericAPI):
    get_all   = APIMethod('get', '/')
    get_byid  = APIMethod('get', '/{id}')
    add_site  = APIMethod('post', '/')
    del_site  = APIMethod('delete', '/{id}')
    edit_site = APIMethod('put', '/{id}')
    set_defaultversion = APIMethod('put', '/{id}/setdefaultversion/{version_id}')
    clone_version = APIMethod('get', '/{id}/cloneversion/{version_id}')
    redirects_new = APIMethod('post', '/{id}/redirects')
    redirects_del = APIMethod('delete', '/{id}/redirects/{redirect_id}')
    redirects_edit = APIMethod('put', '/{id}/redirects/{redirect_id}')
    redirects_getbyid = APIMethod('get', '/{id}/redirects/{redirect_id}')

    def __init__(self, server='http://daspanel-api:8080/1.0', auth=None):
        _headers = {
            'pragma': 'no-cache',
            'Connection': 'close',
            'Accept': 'application/json',
            'Authorization': auth,
        }

        super(SitesApi, self).__init__(
            url = '{}/sites'.format(server),
            auth = None,
            headers = _headers,
            load_json = True,
            throw_on_error = True
        )
        
    def finalize(self, name, result, *args, **kwargs):
        if self.throw_on_error and result.status_code >= 400:
            raise APIError(json.loads(result.content)['detail'], response=result.__dict__)
        if self.load_json:
            return json.loads(result.content)
        return result.content


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    api = SitesApi(server=API_SERVER, auth=current_app.config['DASPANEL_SYS_UUID'])
    try:
        result = api.get_all()
    except APIError as err:
        result = {}
        flash(err, 'error')
    return render_template('/modules/sites/home.html', records=result)

@bp.route('/_get_engines', methods=['GET'])
@login_required
def get_engines():
    """GET /_get_engines: Get engines avaiable
    """
    #def_cfg = {}
    #def_cfg['engines'] = []
    # def_cfg = json.loads(    
    #{"engines": [{"sitetypes": [{"id": "static", "desc": "Static sites"}, {"id": "wordpress", "desc": "Wordpress sites"}], "id": "php70", "desc": "PHP 7.0"}, {"sitetypes": [{"id": "grav", "desc": "Grav sites"}, {"id": "wordpress", "desc": "Wordpress sites"}], "id": "php71", "desc": "PHP 7.1"}, {"sitetypes": [{"id": "static", "desc": "Static sites"}, {"id": "wordpress", "desc": "Wordpress sites"}], "id": "php70", "desc": "PHP 7.0"}]}
    #_engines = current_app.config['DASPANEL']["sys"]["admin"]
    #jmespath.search("engines[?id=='php70']", def_cfg)
    #jmespath.search("engines[*].[id,desc]", def_cfg)
    #jmespath.search("engines[?id=='php70'][id, desc]", def_cfg)
    #jmespath.search("engines[?id=='php70'].{key: id, value: desc}", def_cfg)
    #jmespath.search("engines[?id=='php70'].sitetypes[].[id, desc]", def_cfg)

    return json.dumps(current_app.config['DASPANEL']['engines']), 200, {'ContentType': 'application/json'}

@bp.route('/_get_sitetypes/<engine>', methods=['GET'])
@login_required
def get_sitetypes(engine):
    """GET /_get_config/<cfggroup>: Get config from sysconfig specific section
    """
    #engine = request.args.get('q', '')
    for i, rec in enumerate(current_app.config['DASPANEL']['engines']):
        if rec['runtime'] == engine:
            return json.dumps(rec['sitetypes']), 200, {'ContentType': 'application/json'}

    return json.dumps({'error': 'Engine not found'}), 404, {'ContentType': 'application/json'}

@bp.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    """GET /new: render homepage
    """
    form = NewSiteForm()
    #form.runtime.choices = _engines
    if form.validate_on_submit():
        data = request.form.to_dict()
        data.pop("csrf_token", None)
        api = SitesApi(server=API_SERVER, auth=current_app.config['DASPANEL_SYS_UUID'])
        try:
            result = api.add_site(payload=data)
            flash('Site created successfully', 'message')
            return redirect(url_for('sites.content_fromhttp', recid=result['_cuid']))
        except APIError as err:
            result = {}
            flash(str(err), 'error')

    return render_template('/modules/sites/new.html', form=form)

@bp.route('/delete/<recid>', methods=['GET', 'POST'])
@login_required
def delete(recid):
    """GET/POST /delete: delete site
    """
    api = SitesApi(server=API_SERVER, auth=current_app.config['DASPANEL_SYS_UUID'])
    try:
        result = api.get_byid(id=recid)
    except APIError as err:
        result = {}
        flash(str(err), 'error')
        return redirect(url_for('sites.home'))
    form = DeleteSiteForm()
    if form.validate_on_submit():
        try:
            sitename = result['sitedescription']
            result = api.del_site(id=recid)
            flash('Site successfully deleted: ' + ' ' + sitename, 'message')
            return redirect(url_for('sites.home'))
        except APIError as err:
            result = {}
            flash(str(err), 'error')
            return redirect(url_for('sites.delete', recid=recid))
    return render_template('/modules/sites/delete.html', form=form, record=result)

@bp.route('/edit/<recid>', methods=['GET', 'POST'])
@login_required
def edit(recid):
    """GET/POST /edit: edit site
    """
    api = SitesApi(server=API_SERVER, auth=current_app.config['DASPANEL_SYS_UUID'])
    try:
        result = api.get_byid(id=recid)
    except APIError as err:
        result = {}
        flash(str(err), 'error')
        return redirect(url_for('sites.home'))
    form = EditSiteForm(request.form, **result)
    if form.validate_on_submit():
        data = request.form.to_dict()
        data.pop("csrf_token", None)
        try:
            result = api.edit_site(id=recid, payload=data)
            flash('Site edited successfully: ' + ' ' + data['sitedescription'], 'message')
            return redirect(url_for('sites.home'))

daspanel_web/modules/system/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Daspanel CP system module
~~~~~~~~~~~~~~~~~~~~~~~~~~~

System module for Daspanel web control panel.

:copyright: (c) 2017 by Abner G Jacobsen
:licence: GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
import logging

__title__ = 'Daspanel system module'
__summary__ = 'System module for Daspanel web control panel.'
__uri__ = 'https://github.com/daspanel/cpweb'

__version__ = '0.0.1'

__author__ = 'Abner G Jacobsen'
__email__ = 'abner@apoana.com.br'

__license__ = 'GNU General Public License v3'
__copyright__ = 'Copyright 2017 Abner G Jacobsen'

# the user should dictate what happens when a logging event occurs
#logging.getLogger(__name__).addHandler(logging.NullHandler())

"""The content module."""
__all__ = ["views"]
from .views import *  # noqa

daspanel_web/templates/default/modules/sites/content_uploadfromhttp.html
{% extends "/shared/modal-list-layout.html" %}


{% block HEADERTAGS %}
{{ super() }} 
<style>
  .mui-panel {
    max-width: 500px;
  }
</style>
{% endblock %}

{% block LISTNAVBAR %}
  <nav id="appbar" class="mui-container-fluid mui-appbar mui--bg-primary">
  <table width="100%" cellspacing="0">
    <tr class="mui--appbar-height">
      <td>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <span class="mui--text-title">Upload Content</span>
      </td>
    </tr>
  </table>
</nav>
{% endblock %}

{% block BODY %}
<div class="mui-panel">
  <form method="post" action="{{ url_for('sites.content_fromhttp', recid=recid) }}" role="form">
    <legend>From remote ZIP file</legend>
    {{ form.csrf_token }} 
    <div class="mui-select">
      {{ form.version(placeholder=form.version.description,
                    autofocus="true") }} 
      <label>{{ form.version.label.text }}</label>
      {% if form.version.errors -%}
        <div class="mui--text-danger">{{ form.version.errors[0] }}</div>
      {%- endif %}
    </div>
    <br><br>
    <div class="mui-select">
      {{ form.auth_type(placeholder=form.auth_type.description) }} 
      <label>{{ form.auth_type.label.text }}</label>
      {% if form.auth_type.errors -%}
        <div class="mui--text-danger">{{ form.auth_type.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-textfield">
      {{ form.user(placeholder=form.user.description, spellcheck="false") }}
      <label>{{ form.user.label.text }}</label>
      {% if form.user.errors -%}
        <div class="mui--text-danger">{{ form.user.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-textfield">
      {{ form.password(placeholder=form.password.description, spellcheck="false") }}
      <label>{{ form.password.label.text }}</label>
      {% if form.password.errors -%}
      <div class="mui--text-danger">{{ form.password.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-textfield">
      {{ form.url(placeholder=form.url.description, spellcheck="false") }}
      <label>{{ form.url.label.text }}</label>
      {% if form.url.errors -%}
      <div class="mui--text-danger">{{ form.url.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-textfield">
      {{ form.directory(placeholder=form.directory.description, spellcheck="false") }}
      <label>{{ form.directory.label.text }}</label>
      {% if form.directory.errors -%}
      <div class="mui--text-danger">{{ form.directory.errors[0] }}</div>
      {%- endif %}
    </div>
    <button type="submit" class="mui-btn mui-btn--primary">Upload Content</button>
  </form>
</div>
{% endblock %}

daspanel_web/templates/default/modules/sites/delete.html
{% extends "/shared/modal-list-layout.html" %}


{% block HEADERTAGS %}
{{ super() }} 
<style>
  .mui-panel {
    max-width: 500px;
  }
</style>
{% endblock %}

{% block LISTNAVBAR %}
  <nav id="appbar" class="mui-container-fluid mui-appbar mui--bg-primary">
  <table width="100%" cellspacing="0">
    <tr class="mui--appbar-height">
      <td>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <span class="mui--text-title">Delete Site</span>
      </td>
    </tr>
  </table>
</nav>
{% endblock %}

{% block BODY %}
<div class="mui-panel">
    <div class="mui-panel">
        {{ record.sitedescription }}
    </div>
    <form method="post" action="{{ url_for('sites.delete', recid=record._cuid) }}" role="form">

        {{ form.csrf_token }} 
        <div class="mui-select">
            {{ form.confirm(placeholder=form.confirm.description, spellcheck="false") }}
            <label>{{ form.confirm.label.text }}</label>
            {% if form.confirm.errors -%}
            <div class="mui--text-danger">{{ form.confirm.errors[0] }}</div>
            {%- endif %}
        </div>
        <button type="submit" class="mui-btn mui-btn--danger">Delete</button>
    </form>
</div>
{% endblock %}

daspanel_web/templates/default/modules/sites/edit.html
{% extends "/shared/modal-list-layout.html" %}


{% block HEADERTAGS %}
{{ super() }} 
<style>
  .mui-panel {
    max-width: 500px;
  }
</style>
{% endblock %}

{% block LISTNAVBAR %}
  <nav id="appbar" class="mui-container-fluid mui-appbar mui--bg-primary">
  <table width="100%" cellspacing="0">
    <tr class="mui--appbar-height">
      <td>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <span class="mui--text-title">Edit Site</span>
      </td>
    </tr>
  </table>
</nav>
{% endblock %}

{% block BODY %}
<div class="mui-panel">
  <form method="post" action="{{ url_for('sites.edit', recid=recid) }}" role="form">
    <legend>Edit Site</legend>
    {{ form.csrf_token }} 
    <div class="mui-textfield">
      {{ form.sitedescription(placeholder=form.sitedescription.description,
                    autofocus="true") }} 
      <label>{{ form.sitedescription.label.text }}</label>
      {% if form.sitedescription.errors -%}
        <div class="mui--text-danger">{{ form.sitedescription.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-textfield">
      {{ form.urlprefix(placeholder=form.urlprefix.description) }} 
      <label>{{ form.urlprefix.label.text }}</label>
      {% if form.urlprefix.errors -%}
        <div class="mui--text-danger">{{ form.urlprefix.errors[0] }}</div>
      {%- endif %}
    </div>
    <button type="submit" class="mui-btn mui-btn--primary">Update site</button>
  </form>
</div>
{% endblock %}

daspanel_web/templates/default/modules/sites/new.html
{% extends "/shared/modal-list-layout.html" %}


{% block HEADERTAGS %}
{{ super() }} 
<style>
  .mui-panel {
    max-width: 500px;
  }
</style>
{% endblock %}

{% block LISTNAVBAR %}
  <nav id="appbar" class="mui-container-fluid mui-appbar mui--bg-primary">
  <table width="100%" cellspacing="0">
    <tr class="mui--appbar-height">
      <td>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <a id="appbar-more-vert" href="{{ url_for('sites.home') }}" class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm">
            <i class="material-icons mui--text-title">arrow_back</i>
        </a>
        <span class="mui--text-title">New Site</span>
      </td>
    </tr>
  </table>
</nav>
{% endblock %}

{% block BODY %}
<div class="mui-panel">
  <form method="post" action="{{ url_for('sites.new', **request.args) }}" role="form">
    <legend>Create a new site</legend>
    {{ form.csrf_token }} 
    <div class="mui-textfield">
      {{ form.sitedescription(placeholder=form.sitedescription.description,
                    autofocus="true") }} 
      <label>{{ form.sitedescription.label.text }}</label>
      {% if form.sitedescription.errors -%}
        <div class="mui--text-danger">{{ form.sitedescription.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-select">
      {{ form.runtime(placeholder=form.runtime.description, spellcheck="false") }}
      <label>{{ form.runtime.label.text }}</label>
      {% if form.runtime.errors -%}
      <div class="mui--text-danger">{{ form.runtime.errors[0] }}</div>
      {%- endif %}
    </div>
    <div class="mui-select">
      {{ form.sitetype(placeholder=form.sitetype.description, spellcheck="false") }}
      <label>{{ form.sitetype.label.text }}</label>
      {% if form.sitetype.errors -%}
        <div class="mui--text-danger">{{ form.sitetype.errors[0] }}</div>
      {%- endif %}
    </div>
    <button type="submit" class="mui-btn mui-btn--primary">Create site</button>
  </form>
</div>
{% endblock %}

{% block FOOTERTAGS %}
{{ h.javascript_tag(h.static('axios.js')) }}
{{ h.javascript_tag(h.static('daspanel-util.js')) }}
<!-- 
https://appelsiini.net/2017/accessing-api-with-javascript/
http://codeheaven.io/how-to-use-axios-as-your-http-client/
https://www.sitepoint.com/comparison-javascript-http-libraries/
-->

<script language="javascript" type="text/javascript">
{% include "/modules/sites/js/sitetypes.js" %}

// Get engines avaiable on page load
window.onload = function init_selects() {
    setEngines();
}

// Dynamic change sitetypes options based on engine selection
bindOnchange("runtime", chgTypes);

</script>
{% endblock %}