daspanel_web/modules/content/views.py
from flask import Blueprint, render_template
from flask_login import login_required

bp = Blueprint('content', __name__)


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    return render_template('/content/home.html')


@bp.route('/feedback', methods=['GET', 'POST'])
def feedback():
    """GET|POST /feedback: feedback form handler
    """
    form = FeedbackForm()
    if form.validate_on_submit():
        # TODO: send feedback to contact@example.com
        return 'ok'

    return render_template('/content/feedback.html', form=form)

daspanel_web/modules/module1/views.py
from flask import Blueprint, render_template
import requests
import json
from devourer import GenericAPI, APIMethod, APIError

bp = Blueprint('module1', __name__)

class TestApi(GenericAPI):
    users = APIMethod('get', '/api/?results={count}')

    def __init__(self, headers=None):
        params = {
            'url': 'https://randomuser.me',
            'auth': None,
            'load_json': True,
            'throw_on_error': True,
            'headers': headers
        }
        super(TestApi, self).__init__(**params)


@bp.route('/', methods=['GET'])
def home():
    """GET /: render homepage
    """
    myheaders={
        "pragma": "no-cache",
        "Accept": "application/json",
        "Authorization": "civmw76wg000001p2dwqxpvet",
    }

    api = TestApi(headers=myheaders)
    myusers = api.users(count=1)
    print myusers
    
    result = requests.get("https://randomuser.me/api/?results=5",
        headers={
            "pragma": "no-cache"
        },
        cookies={},
    )
    output = json.loads(result.content)
    #for rec in output['results']:
    #    print rec

    return render_template('/modules/module1/home.html', records=output['results'])

daspanel_web/modules/services/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Daspanel CP Web

Daspanel control panel for web

 :copyright: (c) 2017, Abner G Jacobsen.
             All rights reserved.
 :license:   GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from flask_login import login_required

bp = Blueprint('services', __name__)


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    return render_template('/modules/services/home.html')

daspanel_web/modules/system/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Daspanel CP Web

Daspanel control panel for web

 :copyright: (c) 2017, Abner G Jacobsen.
             All rights reserved.
 :license:   GNU General Public License v3, see LICENSE for more details.
"""
from __future__ import absolute_import, division, print_function
import os

from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from flask_login import login_required

bp = Blueprint('system', __name__)


@bp.route('/', methods=['GET'])
@login_required
def home():
    """GET /: render homepage
    """
    return render_template('/modules/system/home.html')

@bp.route('/services/users', methods=['GET'])
@login_required
def services_users():
    """GET /: render credentials info
    """
    return render_template('/modules/system/services_users.html', cfg=current_app.config['DASPANEL'], env=os.environ)

daspanel_web/templates/default/shared/base-layout.html
{% extends "/skeleton.html" %}


{% block HEADERTAGS %}
{{ h.stylesheet_tag('//cdn.muicss.com/mui-0.9.9/css/mui.min.css') }}
{{ h.stylesheet_tag(h.static('style.css')) }}
{{ h.javascript_tag(h.static('script.js')) }}
<script>
  window.addEventListener('load', function() {
    loadjs('//cdn.muicss.com/mui-0.9.8/js/mui.min.js', 'mui');
  });
</script>

{% endblock %}


{% block HTML %}
   <div id="sidedrawer" class="mui--no-user-select">
      <div id="sidedrawer-brand" class="mui--appbar-line-height">
        <span class="mui--text-title">Daspanel</span>
      </div>
      <div class="mui-divider"></div>
      {% if g.user.is_authenticated: %}
      <ul>
        <li><a href="{{ url_for('content.home') }}"><strong>Dashboard</strong></a></li>
        <li><a href="{{ url_for('sites.home') }}"><strong>Sites</strong></a></li>
        <!-- <li><a href="{{ url_for('module1.home') }}"><strong>Module1</strong></a></li> -->
        <li><a href="{{ url_for('services.home') }}"><strong>Services</strong></a></li>
        <!-- <li><a href="{{ url_for('system.home') }}"><strong>System</strong></a></li> -->
        <li>
            <strong>System</strong>
            <ul>
                <li><a href="{{ url_for('system.services_users') }}"><strong>Services Users</strong></a></li>
            </ul>
        </li>
        <li><a href="{{ url_for('auth.create_account') }}"><strong>New User</strong></a></li>
        <li><a href="{{ url_for('auth.logout') }}"><strong>Log out</strong></a></li>
        <div class="mui-divider"></div>
        <li><strong>{{ g.user.email }}</strong></li>
      </ul>
      
      {% else: %}
      <ul>
        <li><a href="{{ url_for('auth.login') }}"><strong>Log in</strong></a></li>
        <li><a href="{{ url_for('auth.create_account') }}"><strong>Sign up</strong></a></li>
      </ul>
      {% endif %}
    </div>
    {% with messages = get_flashed_messages(with_categories=true) -%}
    {% if messages -%}
    <div id="flash-wrapper">
        <div class="mui--appbar-height"></div>
        <div class="mui-col-xs-12"><br></div>
        <div class="mui-col-xs-12">
            {% for category, message in messages: %}
                {% if category == 'error' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-danger">
                        {{ message }}
                    </div>
                {% elif category == 'warning' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-accent-light">
                        {{ message }}
                    </div>
                {% else: %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-primary-light">
                        {{ message }}
                    </div>

                {% endif %}
            {% endfor %}
        </div>

    </div>
    {% endif %}
    {% endwith %}

    {% block BODY %}{% endblock %}

{% endblock %}

daspanel_web/templates/default/shared/modal-layout.html
{% extends "/shared/base-layout.html" %}



{% block HTML %}

  <nav id="appbar" class="mui-container-fluid mui-appbar mui--bg-primary">
  <table width="100%" cellspacing="0">
    <tr class="mui--appbar-height">
      <td>
        <a class="mui--text-title mui--text-white" href="{{ url_for('sites.home') }}">
            <i class="material-icons">arrow_back</i>
        </a>
        <span class="mui--text-title mui--text-white">New Site</span>
      </td>
    </tr>
  </table>
</nav>

    <div id="content-wrapper">
      <div class="mui--appbar-height"></div>
    {% with messages = get_flashed_messages(with_categories=true) -%}
    {% if messages -%}
    <div id="flash-wrapper">
        <div class="mui--appbar-height"></div>
        <div class="mui-col-xs-12"><br></div>
        <div class="mui-col-xs-12">
            {% for category, message in messages: %}
                {% if category == 'error' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-danger">
                        {{ message }}
                    </div>
                {% elif category == 'warning' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-accent-light">
                        {{ message }}
                    </div>
                {% else: %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-primary-light">
                        {{ message }}
                    </div>

                {% endif %}
            {% endfor %}
        </div>

    </div>
    {% endif %}
    {% endwith %}


      <div class="mui-container-fluid">
        {% block BODY %}{% endblock %}
      </div>
    </div>
{% endblock %}

daspanel_web/templates/default/shared/modal-list-layout.html
{% extends "/shared/base-layout.html" %}



{% block HTML %}
    {% block LISTNAVBAR %}{% endblock %}

    <div id="content-wrapper">
      <div class="mui--appbar-height"></div>
    {% with messages = get_flashed_messages(with_categories=true) -%}
    {% if messages -%}
    <div id="flash-wrapper">
        <div class="mui--appbar-height"></div>
        <div class="mui-col-xs-12"><br></div>
        <div class="mui-col-xs-12">
            {% for category, message in messages: %}
                {% if category == 'error' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-danger">
                        {{ message }}
                    </div>
                {% elif category == 'warning' %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-accent-light">
                        {{ message }}
                    </div>
                {% else: %}
                    <div class="mui-col-xs-12 mui-panel mui--bg-primary-light">
                        {{ message }}
                    </div>

                {% endif %}
            {% endfor %}
        </div>

    </div>
    {% endif %}
    {% endwith %}


      <div class="mui-container-fluid">
        {% block BODY %}{% endblock %}
      </div>
    </div>
{% endblock %}